### ISSUE TITLE
lazy.frame may be failing on forked processes

### ISSUE THREAD

**Issue by kaneplusplus** [bwlewis/lazy.frame#1]
``` r
> require(foreach)
> require(doMC)
> registerDoMC()
> data <- lazy.frame(file="1988.csv", stringsAsFactors=FALSE, sep=",", header=TRUE)
> 
> ids <- foreach(i=isplitIndices(nrow(data),chunkSize=1000000),
+                counter=icount()) %dopar% {
+   xc <- data[i, ]
+   print(counter) 
+   which(xc$Year == 1987 | xc$Year == 2008) + (i[1]-1)
+ }
[1] 1
[1] 2
[1] 3
Error in { : task 4 failed - "line 29 did not have 29 elements"
```

If I run this with %do% I don't get the task failure. Also, if I copy and paste the line where data is created into the foreach loop I don't get the task failure.

**Comment by kaneplusplus** [comment]
Tried this on a different machine and there were no problems. The original machine has been in need of a restart (after kernel updates) for a couple of weeks now.

**Comment by bwlewis** [comment]
Note that '==' is threaded inside lazy.frames on non-windows computers. It's unlikely that doMC can be faster.

**Comment by kaneplusplus** [comment]
OK, I'm still getting the problem. Here's an example with the airline data set where I'm trying to get the unique Origin and Destination variables. Here's the code:

``` r
data <- lazy.frame(file="/tmp/airline/1988.csv",
  stringsAsFactors=FALSE, sep=",", header=TRUE)

uniques <- function(data, cols) {
  unique_list <- foreach(i=isplitIndices(nrow(data), chunkSize=500000)) %:%  
    foreach (col=cols) %do% {
      unique(data[i,col])
    }

  foreach (i=1:length(cols)) %dopar% {
    unique(Reduce(`c`, Map(function(x) x[[i]], unique_list)))
  }

}


ad_encoding <- uniques(data, c("Dest", "Origin"))
```

Here's the error:

``` r
Error in { : 
  task 1 failed - "task 1 failed - "line 40 did not have 29 elements""
```

Change the %dopar% to %do% and it works fine. I'm on an ext4 filesystem.

**Comment by bwlewis** [comment]
Maybe a threading issue. Did you try:

options(lazy.frame.threads=1L)

**Comment by bwlewis** [comment]
Wait, I know the problem. Look in the source code, lazy frame extensively uses seek, rewind, etc. to position around the file.

Since you are forking, all children share the same open file descriptor, but then they are seeking around the file, ruining sequential reads by their siblings.

There is no easy way to support fork here.

Why is seek used? Two reasons:
1. Seek/read leverages readahead very effectively, so it's very good at quickly pulling out blocks of lines.
2. I wanted to natively support gzipped files.

Alternatives:
1. Memory map the file, but then it's much harder to support gzipped files, and that's a major re-write.
2. Don't share the file descriptor. That means reorganizing your foreach loop to open the file inside the loop, separately in each child.

The bummer about alternative #2 is that there is a startup cost to build a table of newline positions in the file, and you only need to do this once.

It might be possible to lightly modify the code to avoid this if you already know it. I'll look into that.

**Comment by bwlewis** [comment]
The gzip option is nice, by the way. If you have a slow disk and a fast CPU, then it's faster to work directly off the compressed file.

**Comment by bwlewis** [comment]
OK Mike, try the latest commit. You can now make a derived lazy.frame from another lazy.frame. The derived lazy.frame uses all the state from the parent except for the file descriptor, and should be safe to use in forked sessions.

So the idea is roughly:

x = lazy.frame("file")

foreach(iterator) %dopar% {
  y = lazy.frame(x)
  do something with y...
}

The derived lazy frames are reasonably cheap to make so this should be reasonably efficient.

**Comment by bwlewis** [comment]
Here is a self-contained example of the new approach (I'm not sure where isplitindices comes from). Note that we create an initial lazy.frame reference (the variable `data`) and then new ones in each foreach loop (`y`) that use the state from that reference, benefitting from copy on write in the doMC fork.

```
library("lazy.frame")
data(iris)
f <- tempfile()
write.table(iris, file=f, sep=",",col.names=TRUE,row.names=FALSE)

library("foreach")
library("doMC")
registerDoMC(5)
data <- lazy.frame(file=f, stringsAsFactors=FALSE, sep=",", header=TRUE)
ids <- foreach(i=split(1:nrow(data),1:10)) %dopar% {
   y <- lazy.frame(file=data, stringsAsFactors=FALSE, sep=",", header=TRUE)
   xc <- y[i, ]
   i[which(xc$Species == "versicolor")]
}

cat("foreach:\n")
print(unlist(ids))

cat("\nlocal:\n")
print(which(iris$Species=="versicolor"))
```

There is some extra overhead for opening a new file descriptor in each child, but not nearly as much as in the initial lazy.frame call.

Let me know if this works on your data.
